# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  checkout-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

  setup-go:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

  build:
    needs: [checkout-code, setup-go]
    runs-on: ubuntu-latest
    steps:
    - name: Build Project
      run: go build -v ./...
      working-directory: ${{ github.workspace }}

  test:
    needs: setup-go
    runs-on: ubuntu-latest
    steps:
    - name: Run Tests
      run: go test -v ./...
      working-directory: ${{ github.workspace }}

